In [ ]:
import cv2 as cv
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
im = cv.imread("Input_Images/940_079A_lt_g.jpg")

In [155]:
im_csv = pd.read_csv("center_circle_coor.csv",delimiter=",")

In [156]:
im_csv.head()

,0,1,2,3,4,5,6,7,8,9,...,53,54,55,56,57,58,59,60,61,62
0,730_012A_1.jpg,177.0,152.0,191.212670,152.0,190.902089,154.954980,189.983920,157.780814,188.498292,...,184.106335,139.691466,186.510133,141.437928,188.498292,143.646002,189.983920,146.219186,190.902089,149.045020
1,730_012A_1_g.jpg,204.0,194.0,219.264338,194.0,218.930775,197.173634,217.944666,200.208565,216.349108,...,211.632169,180.780696,214.213835,182.656387,216.349108,185.027848,217.944666,187.791435,218.930775,190.826366
2,730_012A_10.jpg,179.0,168.0,191.083046,168.0,190.819002,170.512207,190.038412,172.914618,188.775390,...,185.041523,157.535775,187.085136,159.020547,188.775390,160.897764,190.038412,163.085382,190.819002,165.487793
3,730_012A_10_g.jpg,172.0,199.0,186.764823,199.0,186.442176,202.069779,185.488337,205.005395,183.944993,...,179.382412,186.213288,181.879595,188.027598,183.944993,190.321455,185.488337,192.994605,186.442176,195.930221
4,730_012A_2.jpg,176.0,151.0,189.038405,151.0,188.753484,153.710837,187.911175,156.303197,186.548291,...,182.519202,139.708410,184.724396,141.310577,186.548291,143.336218,187.911175,145.696803,188.753484,148.289163

In [167]:
im_csv = pd.read_csv("center_circle_coor.csv",delimiter=",")
dist = 55
center_dia_cropped = np.zeros((62,1))
for ii in range (im_csv.shape[0]):
    im = cv.imread("Input_Images/{}".format(im_csv["0"].iloc[ii]))
    im_coor = im_csv.iloc[ii].values
    im_g = cv.cvtColor(im,cv.COLOR_BGR2GRAY)
    im_ = (im_g * (200 / 255)).astype(np.uint8)
    update_list = np.zeros(1)
    
    for i in range (31):
        cv.circle(im_, (int(im_coor[2*i+1]),int(im_coor[2*i+2])), 0, (255, 255, 255), -1)
        update_list = np.append(update_list,(int(im_coor[2*i+1])-(int(im_coor[1]))+dist))
        update_list = np.append(update_list,(int(im_coor[2*i+2])-(int(im_coor[2]))+dist))
        mask_cr = mask2[int(im_coor[2])-dist:int(im_coor[2])+dist,int(im_coor[1])-dist:int(im_coor[1])+dist]
        im_cr = im[int(im_coor[2])-dist:int(im_coor[2])+dist,int(im_coor[1])-dist:int(im_coor[1])+dist,:]
    
    update_list = update_list[1:]
    center_dia_cropped = np.concatenate((center_dia_cropped,np.resize(update_list,(62,1))),axis=1)
    cv.imwrite("Input_Images_resized/{}".format(im_csv["0"].iloc[ii]),im_cr)  # Kalite varsayılan: 95 (0-100 arası)
    cv.imwrite("Input_Images_resized_marked/{}".format(im_csv["0"].iloc[ii]),im_)
center_dia_cropped = center_dia_cropped[:,1:]

In [170]:
center_dia_cropped = np.concatenate((np.resize(im_csv["0"].values,(516,1)),center_dia_cropped.T),axis=1)
pd.DataFrame(center_dia_cropped).to_csv("center_dia_cropped.csv",index=False)

In [171]:
pd.read_csv("center_dia_cropped.csv",delimiter=",")

,0,1,2,3,4,5,6,7,8,9,...,53,54,55,56,57,58,59,60,61,62
0,730_012A_1.jpg,55.0,55.0,69.0,55.0,68.0,57.0,67.0,60.0,66.0,...,62.0,42.0,64.0,44.0,66.0,46.0,67.0,49.0,68.0,52.0
1,730_012A_1_g.jpg,55.0,55.0,70.0,55.0,69.0,58.0,68.0,61.0,67.0,...,62.0,41.0,65.0,43.0,67.0,46.0,68.0,48.0,69.0,51.0
2,730_012A_10.jpg,55.0,55.0,67.0,55.0,66.0,57.0,66.0,59.0,64.0,...,61.0,44.0,63.0,46.0,64.0,47.0,66.0,50.0,66.0,52.0
3,730_012A_10_g.jpg,55.0,55.0,69.0,55.0,69.0,58.0,68.0,61.0,66.0,...,62.0,42.0,64.0,44.0,66.0,46.0,68.0,48.0,69.0,51.0
4,730_012A_2.jpg,55.0,55.0,68.0,55.0,67.0,57.0,66.0,60.0,65.0,...,61.0,43.0,63.0,45.0,65.0,47.0,66.0,49.0,67.0,52.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,mv_850_rt.jpg,55.0,55.0,64.0,55.0,64.0,57.0,63.0,59.0,62.0,...,59.0,46.0,61.0,47.0,62.0,49.0,63.0,50.0,64.0,52.0
512,mv_850_rb.jpg,55.0,55.0,63.0,55.0,63.0,56.0,62.0,58.0,61.0,...,59.0,47.0,60.0,48.0,61.0,49.0,62.0,51.0,63.0,53.0
513,mv_850_lb.jpg,55.0,55.0,65.0,55.0,65.0,57.0,64.0,59.0,63.0,...,60.0,46.0,61.0,47.0,63.0,48.0,64.0,50.0,65.0,52.0
514,mv_850_lt.jpg,55.0,55.0,65.0,55.0,64.0,57.0,64.0,59.0,63.0,...,60.0,46.0,61.0,47.0,63.0,49.0,64.0,50.0,64.0,52.0
515,mv_850_cam.jpg,55.0,55.0,63.0,55.0,63.0,56.0,62.0,58.0,61.0,...,59.0,47.0,60.0,48.0,61.0,49.0,62.0,51.0,63.0,53.0

In [123]:
for i in range (31):
    cv.circle(im_, (int(im_coor[2*i+1]),int(im_coor[2*i+2])), 0, (255, 255, 255), -1)

In [124]:
cv.imshow("r",im_)
cv.waitKey(0)

-1

In [101]:
lower_green= np.array([250])
upper_green = np.array([255])
mask2 = cv.inRange(im_, lower_green, upper_green)
cv.imshow("r",mask2)
cv.waitKey(0)

-1

In [89]:
dist = 70
mask_cr = mask2[int(im_coor[2])-dist:int(im_coor[2])+dist,int(im_coor[1])-dist:int(im_coor[1])+dist]
im_cr = im[int(im_coor[2])-dist:int(im_coor[2])+dist,int(im_coor[1])-dist:int(im_coor[1])+dist,:]
cv.imshow("r",mask_cr)
cv.imshow("a",im_cr)
cv.waitKey(0)

-1

In [96]:
cv.imshow("b",im[:,:,0])
cv.imshow("g",im[:,:,1])
cv.imshow("r",im[:,:,2])
cv.waitKey(0)

-1

In [71]:
im_r = cv.resize(im[:,:,2], (400,400))
im_b = cv.resize(im[:,:,0], (400,400))
im_g = cv.resize(im[:,:,1], (400,400))

In [68]:
cv.imshow("a",im_resize)
cv.waitKey(0)

-1

In [89]:
ret, th_r = cv.threshold(im_r,170,255,cv.THRESH_BINARY)
ret, th_b = cv.threshold(im_b,50,255,cv.THRESH_BINARY_INV)
ret, th_g = cv.threshold(im_g,50,255,cv.THRESH_BINARY_INV)

In [90]:
cv.imshow("r",th_r)
#cv.imshow("b",th_b)
#cv.imshow("g",th_g)
cv.waitKey(0)

-1

In [156]:
lower_red = np.array([30,30,135])
upper_red = np.array([90,90,180])
mask1 = cv.inRange(im, lower_red, upper_red)
cv.imshow("r",mask1)
cv.waitKey(0)

-1

In [157]:
lower_green= np.array([35,200,35])
upper_green = np.array([85,250,85])
mask2 = cv.inRange(im, lower_green, upper_green)
cv.imshow("r",mask2)
cv.waitKey(0)

-1

In [246]:
center = np.array(list(zip(*np.where(mask2 == 255))))

In [247]:
center_point = np.array(center.mean(axis=0))

In [248]:
pupil = list(zip(*np.where(mask1 == 255)))

In [213]:
pupil

[(156, 222),
 (156, 223),
 (156, 224),
 (156, 225),
 (156, 226),
 (156, 227),
 (156, 228),
 (156, 229),
 (156, 230),
 (156, 231),
 (156, 232),
 (156, 233),
 (156, 234),
 (156, 235),
 (157, 223),
 (157, 224),
 (157, 225),
 (157, 227),
 (157, 228),
 (157, 229),
 (157, 230),
 (157, 231),
 (157, 232),
 (157, 233),
 (157, 234),
 (158, 218),
 (158, 219),
 (158, 220),
 (158, 237),
 (158, 238),
 (158, 239),
 (159, 218),
 (159, 219),
 (159, 220),
 (159, 237),
 (159, 238),
 (160, 240),
 (161, 216),
 (162, 214),
 (162, 215),
 (163, 214),
 (163, 215),
 (163, 243),
 (166, 212),
 (167, 212),
 (168, 246),
 (169, 210),
 (169, 211),
 (169, 246),
 (170, 210),
 (170, 211),
 (170, 246),
 (170, 247),
 (171, 211),
 (171, 246),
 (171, 247),
 (172, 210),
 (172, 246),
 (172, 247),
 (173, 210),
 (173, 246),
 (173, 247),
 (174, 210),
 (174, 246),
 (174, 247),
 (175, 210),
 (175, 247),
 (176, 210),
 (176, 246),
 (176, 247),
 (177, 210),
 (177, 246),
 (177, 247),
 (178, 210),
 (178, 246),
 (178, 247),
 (179, 210),
 (179, 246),
 (179, 247),
 (180, 210),
 (180, 246),
 (180, 247),
 (181, 211),
 (181, 246),
 (181, 247),
 (182, 210),
 (182, 211),
 (182, 246),
 (182, 247),
 (183, 210),
 (183, 246),
 (184, 212),
 (184, 245),
 (185, 213),
 (185, 245),
 (188, 214),
 (188, 215),
 (188, 243),
 (189, 214),
 (189, 242),
 (191, 217),
 (192, 238),
 (193, 220),
 (193, 237),
 (193, 238),
 (194, 223),
 (194, 224),
 (194, 231),
 (194, 232),
 (194, 233),
 (194, 234),
 (195, 223),
 (195, 224),
 (195, 225),
 (195, 226),
 (195, 227),
 (195, 228),
 (195, 229),
 (195, 230),
 (195, 231),
 (195, 232)]

In [249]:
import random
pupil_points = np.array(random.sample(pupil, 20))

In [250]:
pupil_points[:, [1, 0]] = pupil_points[:, [0, 1]]
center_point[[1, 0]] = center_point[[0, 1]]

In [252]:
im_copy = mask2.copy()
for i in pupil_points:
    im_copy = cv.circle(im_copy,i,2,(255, 0, 0),-1)

In [253]:
im_copy = cv.circle(im_copy,center_point.astype(int),2,(255, 0, 0),-1)

In [254]:
cv.imshow("a",im_copy)
cv.waitKey(0)

-1

In [ ]:
ml_targets_center = pd.DataFrame(center_list)

In [261]:
name_list = pd.read_csv("real_values_2.csv",delimiter=";").iloc[:,0].values

array(['730_012A_1.jpg', '730_012A_1_g.jpg', '730_012A_10.jpg',
       '730_012A_10_g.jpg', '730_012A_2.jpg', '730_012A_2_g.jpg',
       '730_012A_3.jpg', '730_012A_3_g.jpg', '730_012A_4.jpg',
       '730_012A_4_g.jpg', '730_012A_5.jpg', '730_012A_5_g.jpg',
       '730_012A_6.jpg', '730_012A_6_g.jpg', '730_012A_7.jpg',
       '730_012A_7_g.jpg', '730_012A_8.jpg', '730_012A_8_g.jpg',
       '730_012A_9.jpg', '730_012A_9_g.jpg', '730_012A_cam.jpg',
       '730_012A_cam_g.jpg', '730_012A_lb.jpg', '730_012A_lb_g.jpg',
       '730_012A_lt.jpg', '730_012A_lt_g.jpg', '730_012A_rb.jpg',
       '730_012A_rb_g.jpg', '730_012A_rt.jpg', '730_012A_rt_g.jpg',
       '730_037A_1.jpg', '730_037A_1_g.jpg', '730_037A_10.jpg',
       '730_037A_10_g.jpg', '730_037A_2.jpg', '730_037A_2_g.jpg',
       '730_037A_3.jpg', '730_037A_3_g.jpg', '730_037A_4.jpg',
       '730_037A_4_g.jpg', '730_037A_5.jpg', '730_037A_5_g.jpg',
       '730_037A_6.jpg', '730_037A_6_g.jpg', '730_037A_7.jpg',
       '730_037A_7_g.jpg', '730_037A_8.jpg', '730_037A_8_g.jpg',
       '730_037A_9.jpg', '730_037A_9_g.jpg', '730_037A_cam.jpg',
       '730_037A_cam_g.jpg', '730_037A_lb.jpg', '730_037A_lb_g.jpg',
       '730_037A_lt.jpg', '730_037A_lt_g.jpg', '730_037A_rb.jpg',
       '730_037A_rb_g.jpg', '730_037A_rt.jpg', '730_037A_rt_g.jpg',
       '730_060A_1.jpg', '730_060A_1_g.jpg', '730_060A_10.jpg',
       '730_060A_10_g.jpg', '730_060A_2.jpg', '730_060A_2_g.jpg',
       '730_060A_3.jpg', '730_060A_3_g.jpg', '730_060A_4.jpg',
       '730_060A_4_g.jpg', '730_060A_5.jpg', '730_060A_5_g.jpg',
       '730_060A_6.jpg', '730_060A_6_g.jpg', '730_060A_7.jpg',
       '730_060A_7_g.jpg', '730_060A_8.jpg', '730_060A_8_g.jpg',
       '730_060A_9.jpg', '730_060A_9_g.jpg', '730_060A_cam.jpg',
       '730_060A_cam_g.jpg', '730_060A_lb.jpg', '730_060A_lb_g.jpg',
       '730_060A_lt.jpg', '730_060A_lt_g.jpg', '730_060A_rb.jpg',
       '730_060A_rb_g.jpg', '730_060A_rt.jpg', '730_060A_rt_g.jpg',
       '730_084A_1.jpg', '730_084A_1_g.jpg', '730_084A_10.jpg',
       '730_084A_10_g.jpg', '730_084A_2.jpg', '730_084A_2_g.jpg',
       '730_084A_3.jpg', '730_084A_3_g.jpg', '730_084A_4.jpg',
       '730_084A_4_g.jpg', '730_084A_5.jpg', '730_084A_5_g.jpg',
       '730_084A_6.jpg', '730_084A_6_g.jpg', '730_084A_7.jpg',
       '730_084A_7_g.jpg', '730_084A_8.jpg', '730_084A_8_g.jpg',
       '730_084A_9.jpg', '730_084A_9_g.jpg', '730_084A_cam.jpg',
       '730_084A_cam_g.jpg', '730_084A_lb.jpg', '730_084A_lb_g.jpg',
       '730_084A_lt.jpg', '730_084A_lt_g.jpg', '730_084A_rb.jpg',
       '730_084A_rb_g.jpg', '730_084A_rt.jpg', '730_084A_rt_g.jpg',
       '730_103A_1.jpg', '730_103A_1_g.jpg', '730_103A_10.jpg',
       '730_103A_10_g.jpg', '730_103A_2.jpg', '730_103A_2_g.jpg',
       '730_103A_3.jpg', '730_103A_3_g.jpg', '730_103A_4.jpg',
       '730_103A_4_g.jpg', '730_103A_5.jpg', '730_103A_5_g.jpg',
       '730_103A_6.jpg', '730_103A_6_g.jpg', '730_103A_7.jpg',
       '730_103A_7_g.jpg', '730_103A_8.jpg', '730_103A_8_g.jpg',
       '730_103A_9.jpg', '730_103A_9_g.jpg', '730_103A_cam.jpg',
       '730_103A_cam_g.jpg', '730_103A_lb.jpg', '730_103A_lb_g.jpg',
       '730_103A_lt.jpg', '730_103A_lt_g.jpg', '730_103A_rb.jpg',
       '730_103A_rb_g.jpg', '730_103A_rt.jpg', '730_103A_rt_g.jpg',
       '850_017A_G.jpg', '850_017A_1.jpg', '850_017A_1_g.jpg',
       '850_017A_10.jpg', '850_017A_10_g.jpg', '850_017A_2.jpg',
       '850_017A_2_g.jpg', '850_017A_3.jpg', '850_017A_3_g.jpg',
       '850_017A_4.jpg', '850_017A_4_g.jpg', '850_017A_5.jpg',
       '850_017A_5_g.jpg', '850_017A_6.jpg', '850_017A_6_g.jpg',
       '850_017A_7.jpg', '850_017A_7_g.jpg', '850_017A_8.jpg',
       '850_017A_8_g.jpg', '850_017A_9.jpg', '850_017A_9_g.jpg',
       '850_017A_cam.jpg', '850_017A_cam_g.jpg', '850_017A_lb.jpg',
       '850_017A_lb_g.jpg', '850_017A_lt.jpg', '850_017A_lt_g.jpg',
       '850_017A_rb.jpg', '850_017A_rb_g.jpg', '850_017A_rt.jpg',
       '850_017A_rt_g.jpg', '940_026A_1.jpg', '940_026A_1_g.jpg',
       '940_026A_10.jpg', '940_026A_10_g.jpg', '940_026A_2.jpg',
       '940_026A_2_g.jpg', '940_026A_3.jpg', '940_026A_3_g.jpg',
       '940_026A_4.jpg', '940_026A_4_g.jpg', '940_026A_5.jpg',
       '940_026A_5_g.jpg', '940_026A_6.jpg', '940_026A_6_g.jpg',
       '940_026A_7.jpg', '940_026A_7_g.jpg', '940_026A_8.jpg',
       '940_026A_8_g.jpg', '940_026A_9.jpg', '940_026A_9_g.jpg',
       '940_026A_cam.jpg', '940_026A_cam_g.jpg', '940_026A_lb.jpg',
       '940_026A_lb_g.jpg', '940_026A_lt.jpg', '940_026A_lt_g.jpg',
       '940_026A_rb.jpg', '940_026A_rb_g.jpg', '940_026A_rt.jpg',
       '940_026A_rt_g.jpg', '850_040A_1.jpg', '850_040A_1_g.jpg',
       '850_040A_10.jpg', '850_040A_10_g.jpg', '850_040A_2.jpg',
       '850_040A_2_g.jpg', '850_040A_3.jpg', '850_040A_3_g.jpg',
       '850_040A_4.jpg', '850_040A_4_g.jpg', '850_040A_5.jpg',
       '850_040A_5_g.jpg', '850_040A_6.jpg', '850_040A_6_g.jpg',
       '850_040A_7.jpg', '850_040A_7_g.jpg', '850_040A_8.jpg',
       '850_040A_8_g.jpg', '850_040A_9.jpg', '850_040A_9_g.jpg',
       '850_040A_cam.jpg', '850_040A_cam_g.jpg', '850_040A_lb.jpg',
       '850_040A_lb_g.jpg', '850_040A_lt.jpg', '850_040A_lt_g.jpg',
       '850_040A_rb.jpg', '850_040A_rb_g.jpg', '850_040A_rt.jpg',
       '850_040A_rt_g.jpg', '940_048A_1.jpg', '940_048A_1_g.jpg',
       '940_048A_10.jpg', '940_048A_10_g.jpg', '940_048A_2.jpg',
       '940_048A_2_g.jpg', '940_048A_3.jpg', '940_048A_3_g.jpg',
       '940_048A_4.jpg', '940_048A_4_g.jpg', '940_048A_5.jpg',
       '940_048A_5_g.jpg', '940_048A_6.jpg', '940_048A_6_g.jpg',
       '940_048A_7.jpg', '940_048A_7_g.jpg', '940_048A_8.jpg',
       '940_048A_8_g.jpg', '940_048A_9.jpg', '940_048A_9_g.jpg',
       '940_048A_cam.jpg', '940_048A_cam_g.jpg', '940_048A_lb.jpg',
       '940_048A_lb_g.jpg', '940_048A_lt.jpg', '940_048A_lt_g.jpg',
       '940_048A_rb.jpg', '940_048A_rb_g.jpg', '940_048A_rt.jpg',
       '940_048A_rt_g.jpg', '850_065A_1.jpg', '850_065A_1_g.jpg',
       '850_065A_10.jpg', '850_065A_10_g.jpg', '850_065A_2.jpg',
       '850_065A_2_g.jpg', '850_065A_3.jpg', '850_065A_3_g.jpg',
       '850_065A_4.jpg', '850_065A_4_g.jpg', '850_065A_5.jpg',
       '850_065A_5_g.jpg', '850_065A_6.jpg', '850_065A_6_g.jpg',
       '850_065A_7.jpg', '850_065A_7_g.jpg', '850_065A_8.jpg',
       '850_065A_8_g.jpg', '850_065A_9.jpg', '850_065A_9_g.jpg',
       '850_065A_cam.jpg', '850_065A_cam_g.jpg', '850_065A_lb.jpg',
       '850_065A_lb_g.jpg', '850_065A_lt.jpg', '850_065A_lt_g.jpg',
       '850_065A_rb.jpg', '850_065A_rb_g.jpg', '850_065A_rt.jpg',
       '850_065A_rt_g.jpg', '850_078A_1.jpg', '850_078A_1_g.jpg',
       '850_078A_10.jpg', '850_078A_10_g.jpg', '850_078A_2.jpg',
       '850_078A_2_g.jpg', '850_078A_3.jpg', '850_078A_3_g.jpg',
       '850_078A_4.jpg', '850_078A_4_g.jpg', '850_078A_5.jpg',
       '850_078A_5_g.jpg', '850_078A_6.jpg', '850_078A_6_g.jpg',
       '850_078A_7.jpg', '850_078A_7_g.jpg', '850_078A_8.jpg',
       '850_078A_8_g.jpg', '850_078A_9.jpg', '850_078A_9_g.jpg',
       '850_078A_cam.jpg', '850_078A_cam_g.jpg', '850_078A_lb.jpg',
       '850_078A_lb_g.jpg', '850_078A_lt.jpg', '850_078A_lt_g.jpg',
       '850_078A_rb.jpg', '850_078A_rb_g.jpg', '850_078A_rt.jpg',
       '850_078A_rt_g.jpg', '940_079A_1.jpg', '940_079A_1_g.jpg',
       '940_079A_10.jpg', '940_079A_10_g.jpg', '940_079A_2.jpg',
       '940_079A_2_g.jpg', '940_079A_3.jpg', '940_079A_3_g.jpg',
       '940_079A_4.jpg', '940_079A_4_g.jpg', '940_079A_5.jpg',
       '940_079A_5_g.jpg', '940_079A_6.jpg', '940_079A_6_g.jpg',
       '940_079A_7.jpg', '940_079A_7_g.jpg', '940_079A_8.jpg',
       '940_079A_8_g.jpg', '940_079A_9.jpg', '940_079A_9_g.jpg',
       '940_079A_cam.jpg', '940_079A_cam_g.jpg', '940_079A_lb.jpg',
       '940_079A_lb_g.jpg', '940_079A_lt.jpg', '940_079A_lt_g.jpg',
       '940_079A_rb.jpg', '940_079A_rb_g.jpg', '940_079A_rt.jpg',
       '940_079A_rt_g.jpg', '940_102A_1.jpg', '940_102A_1_g.jpg',
       '940_102A_10.jpg', '940_102A_10_g.jpg', '940_102A_2.jpg',
       '940_102A_2_g.jpg', '940_102A_3.jpg', '940_102A_3_g.jpg',
       '940_102A_4.jpg', '940_102A_4_g.jpg', '940_102A_5.jpg',
       '940_102A_5_g.jpg', '940_102A_6.jpg', '940_102A_6_g.jpg',
       '940_102A_7.jpg', '940_102A_7_g.jpg', '940_102A_8.jpg',
       '940_102A_8_g.jpg', '940_102A_9.jpg', '940_102A_9_g.jpg',
       '940_102A_cam.jpg', '940_102A_cam_g.jpg', '940_102A_lb.jpg',
       '940_102A_lb_g.jpg', '940_102A_lt.jpg', '940_102A_lt_g.jpg',
       '940_102A_rb.jpg', '940_102A_rb_g.jpg', '940_102A_rt.jpg',
       '940_102A_rt_g.jpg', '850_104A_1.jpg', '850_104A_1_g.jpg',
       '850_104A_10.jpg', '850_104A_10_g.jpg', '850_104A_2.jpg',
       '850_104A_2_g.jpg', '850_104A_3.jpg', '850_104A_3_g.jpg',
       '850_104A_4.jpg', '850_104A_4_g.jpg', '850_104A_5.jpg',
       '850_104A_5_g.jpg', '850_104A_6.jpg', '850_104A_6_g.jpg',
       '850_104A_7.jpg', '850_104A_7_g.jpg', '850_104A_8.jpg',
       '850_104A_8_g.jpg', '850_104A_9.jpg', '850_104A_9_g.jpg',
       '850_104A_cam.jpg', '850_104A_cam_g.jpg', '850_104A_lb.jpg',
       '850_104A_lb_g.jpg', '850_104A_lt.jpg', '850_104A_lt_g.jpg',
       '850_104A_rb.jpg', '850_104A_rb_g.jpg', '850_104A_rt.jpg',
       '850_104A_rt_g.jpg', '940_150A_1.jpg', '940_150A_1_g.jpg',
       '940_150A_10.jpg', '940_150A_10_g.jpg', '940_150A_2.jpg',
       '940_150A_2_g.jpg', '940_150A_3.jpg', '940_150A_3_g.jpg',
       '940_150A_4.jpg', '940_150A_4_g.jpg', '940_150A_5.jpg',
       '940_150A_5_g.jpg', '940_150A_6.jpg', '940_150A_6_g.jpg',
       '940_150A_7.jpg', '940_150A_7_g.jpg', '940_150A_8.jpg',
       '940_150A_8_g.jpg', '940_150A_9.jpg', '940_150A_9_g.jpg',
       '940_150A_cam.jpg', '940_150A_cam_g.jpg', '940_150A_lb.jpg',
       '940_150A_lb_g.jpg', '940_150A_lt.jpg', '940_150A_lt_g.jpg',
       '940_150A_rb.jpg', '940_150A_rb_g.jpg', '940_150A_rt.jpg',
       '940_150A_rt_g.jpg', 'kh_730_cam2.jpg', 'kh_730_cam2_g.jpg',
       'kh_730_lb2.jpg', 'kh_730_lb2_g.jpg', 'kh_730_lt2.jpg',
       'kh_730_lt2_g.jpg', 'kh_730_rb2.jpg', 'kh_730_rb2_g.jpg',
       'kh_730_rt2.jpg', 'kh_730_rt2_g.jpg', 'kh_850_cam_g.jpg',
       'kh_850_cam2.jpg', 'kh_850_lb_g.jpg', 'kh_850_lb2.jpg',
       'kh_850_lt_g.jpg', 'kh_850_lt2.jpg', 'kh_850_rb_g.jpg',
       'kh_850_rb2.jpg', 'kh_850_rt_g.jpg', 'kh_850_rt2.jpg',
       'kh_940_cam.jpg', 'kh_940_cam_g2.jpg', 'kh_940_cam2.jpg',
       'kh_940_lb.jpg', 'kh_940_lb_g2.jpg', 'kh_940_lb2.jpg',
       'kh_940_lt.jpg', 'kh_940_lt_g2.jpg', 'kh_940_lt2.jpg',
       'kh_940_rb.jpg', 'kh_940_rb_g2.jpg', 'kh_940_rb2.jpg',
       'kh_940_rt.jpg', 'kh_940_rt_g2.jpg', 'kh_940_rt2.jpg',
       'mv_940V_cam.jpg', 'mv_940V_G_cam.jpg', 'mv_940V_G_lb.jpg',
       'mv_940V_G_lt.jpg', 'mv_940V_G_rb.jpg', 'mv_940V_G_rt.jpg',
       'mv_940V_lb.jpg', 'mv_940V_lt.jpg', 'mv_940V_rb.jpg',
       'mv_940V_rt.jpg', 'mv_730_rt_g.jpg', 'mv_730_rb_g.jpg',
       'mv_730_lb_g.jpg', 'mv_730_lt_g.jpg', 'mv_730_cam_g.jpg',
       'mv_730_rt.jpg', 'mv_730_rb.jpg', 'mv_730_lb.jpg', 'mv_730_lt.jpg',
       'mv_730_cam.jpg', 'mv_850_rt_g.jpg', 'mv_850_rb_g.jpg',
       'mv_850_lb_g.jpg', 'mv_850_lt_g.jpg', 'mv_850_cam_g.jpg',
       'mv_850_rt.jpg', 'mv_850_rb.jpg', 'mv_850_lb.jpg', 'mv_850_lt.jpg',
       'mv_850_cam.jpg'], dtype=object)

In [2]:
pd.read_csv("real_values_2.csv",delimiter=";").head()

,FileName,Center (px) (x-axis),Center (px) (y-axis),Diameter (px) (x-axis),Diameter (px) (y-axis),Diameter (px)
0,730_012A_1.jpg,177,152,9,11,"14,2126704"
1,730_012A_1_g.jpg,204,194,8,13,"15,26433752"
2,730_012A_10.jpg,179,168,11,5,"12,08304597"
3,730_012A_10_g.jpg,172,199,13,7,"14,76482306"
4,730_012A_2.jpg,176,151,7,11,"13,03840481"

In [125]:
eye_df = pd.read_csv("real_values_2.csv",delimiter=";")
ml_table = np.zeros(62)
n = 30       # Nokta sayısı
theta = np.linspace(0, 2*np.pi, n, endpoint=False)  # 0'dan 2π'ye kadar açılar
for i in np.arange(0,len(eye_df)):

    h, k = eye_df['Center (px) (x-axis)'].values[i], eye_df['Center (px) (y-axis)'].values[i]       # Çemberin merkezi
    r = float(eye_df['Diameter (px)'].values[i].replace(",", "."))     # Yarıçap
    x = h + r * np.cos(theta)
    y = k + r * np.sin(theta)
    combined = np.column_stack((x, y)).ravel()
    ml_points = np.hstack((np.array(eye_df['Center (px) (x-axis)'].values[i]),np.array(eye_df['Center (px) (y-axis)'].values[i]),combined))
    ml_table = np.vstack((ml_table,ml_points))

In [126]:
ml_table_fin = np.concatenate((np.resize(eye_df.FileName.values,(516,1)),ml_table[1:]),axis=1)

In [127]:
pd.DataFrame(ml_table_fin).to_csv('center_circle_coor.csv',sep=',',index=False)